title: My Blog
description: >-
  Welcome to my blog! Here I share my thoughts and experiences.
baseurl: "/blog" # 仓库名称
url: "https://geyu210.github.io" # 替换为您的 GitHub Pages URL

# 社交链接
github_username: geyu210

# 构建设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 分页
paginate: 5
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/ 